### ISSUE TITLE
短信格式能否支持在应用内自定义

### ISSUE THREAD

**Issue by jdlindu** [xiaomi-sa/alertsystem#1]
如果能在应用内自定义短信格式的正则表达式就更赞了。
或者给出自定义短信格式的提示。
看了下代码感觉二次开发的难度还是不小的。

**Comment by laiwei** [comment]
嗯，这个之前考虑过，没有太想清楚

等等抽时间，再考虑考虑

**Comment by xdongp** [comment]
下一版把他支持短信自定义。

在 2014年4月22日 下午7:47，MrLin notifications@github.com写道：
